### ISSUE TITLE
Missing message macro in AC_CHECK_LIB call

### ISSUE THREAD

**Issue by bturrubiates** [Snaipe/c-smart-pointers#6]
Running configure results in the following message:
```
checking for srunner_run_all in -lcheck... no
../../../dependencies/csptr/configure: line 12116: Could: command not found
checking whether ln -s works... yes
```
I think you probably wanted AC_MSG_ERROR/AC_MSG_NOTICE

Here is the line in question:
https://github.com/Snaipe/c-smart-pointers/blob/master/configure.ac#L16

**Comment by Snaipe** [comment]
Thank you for noticing!
